# Generated by Django 4.1.5 on 2023-03-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bugtracker",
            name="project_number",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
